
- name: Converted adhoc command example
  hosts: all
  become: True   
  tasks:
    
    - name: Create a user 
      user:
        name: "{{ username ['test']['uname'] }}" 
        comment: "{{ username ['test']['description'] }}"
        state: present
        groups: wheel 

   



    
    